name: flags_task
description: A Flags Task made for Nearcast

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  get_it: ^7.2.0
  path_provider: ^2.0.8
  sqflite: ^2.0.1
  splashscreen: ^1.3.5
  google_fonts: ^2.2.0
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/flag.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
