name: flags_task
description: A Flags Task made for Nearcast

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # HTTP requests
  http: ^0.13.4
  # Gets flutter database paths
  path_provider: ^2.0.8
  # SQLite DB
  sqflite: ^2.0.1
  # Fonts library
  google_fonts: ^2.2.0
  # Network checker
  internet_connection_checker: ^0.0.1+3
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/flag.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
